name: Deploy static website
on:
  workflow_call:
    inputs:
      artifact_name:
        type: string
      artifact_path:
        type: string
      s3_bucket:
        type: string
      cloudfront_distribution_id:
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download static files
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}
      - name: Install AWS tools
        run:
          pip install awscli==1.16.311
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Sync static files to S3
        run:
          aws s3 sync ${{ inputs.artifact_path }} s3://${{ inputs.s3_bucket }} --acl public-read --delete
      - name: Invalidate CloudFront edge caches
        run:
          aws cloudfront create-invalidation --distribution-id ${{ inputs.cloudfront_distribution_id }} --paths '/*'
