name: Docker deploy
on:
  workflow_call:
    inputs:
      environment:
        type: string
      ecr_repository:
        type: string
      python_version:
        type: string
        required: true
      region:
        type: string
        default: "eu-west-1"
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v5
        with:
           python-version: '${{ inputs.python_version }}'
      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.6.0
        with:
          version: '3.8.1'
        id: install
      - name: Install AWS tools
        run:
          pip install -r etc/requirements-aws.txt
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Deploy current docker image to AWS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr_repository}}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          sops --decrypt etc/deploy.config.${{ inputs.environment }}.yaml > etc/deploy.config.${{ inputs.environment }}.decrypted.yaml
          ecs-deplojo --config etc/deploy.config.${{ inputs.environment }}.decrypted.yaml --var="image=${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
          rm etc/deploy.config.${{ inputs.environment }}.decrypted.yaml
