name: Docker build
on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: "prd"
      ecr_repository:
        type: string
        required: true
      django_settings_module:
        type: string
        required: true
      region:
        type: string
        default: "eu-west-1"
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      TECHONOMY_REPOS_GITHUB_TOKEN:
        required: false

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.region }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecr_repository}}
        IMAGE_TAG: ${{ github.sha }}
        DOCKER_BUILDKIT: 1
      run: |
        echo ${{ secrets.TECHONOMY_REPOS_GITHUB_TOKEN }} > ./.GITHUB_TOKEN
        aws codeartifact get-authorization-token --domain techonomy-dev --domain-owner 718089050198 --query authorizationToken --output text > ./.AWS_CODEARTIFACT_TOKEN
        docker build --secret id=github_token,src=./.GITHUB_TOKEN --secret id=aws_codeartifact_token,src=./.AWS_CODEARTIFACT_TOKEN --build-arg ENVIRONMENT="${{ inputs.environment }}" --build-arg DJANGO_SETTINGS_MODULE="${{ inputs.django_settings_module }}" -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest . -f etc/docker/Dockerfile
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
