name: Frontend CI
on:
  workflow_call:
    inputs:
      working_directory:
        type: string
        required: false
        default: "."
      node_version:
        type: string
        required: true
    secrets:
      PACKAGE_GITHUB_TOKEN:
        required: false
      TECHONOMY_REPOS_GITHUB_TOKEN:
        required: true
      FONTAWESOME_NPM_AUTH_TOKEN:
        required: false

jobs:
  linting-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TECHONOMY_REPOS_GITHUB_TOKEN }}
      - name: Setup node ${{ inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
      - name: Configure NPM package repository
        working-directory: ${{ inputs.working_directory }}
        run: |
          npx yarn config set @techonomydev:registry https://npm.pkg.github.com/
          npm set https://npm.pkg.github.com/:_authToken ${{ secrets.TECHONOMY_REPOS_GITHUB_TOKEN }}
          npm set @fortawesome:registry https://npm.fontawesome.com/
          npm set //npm.fontawesome.com/:_authToken ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
      - name: Configure git
        run: |
          git config --global url."https://${{ secrets.TECHONOMY_REPOS_GITHUB_TOKEN }}@github.com/".insteadOf git@github.com:
      - name: Install front-end dependencies
        working-directory: ${{ inputs.working_directory }}
        run: |
          npx yarn install
      - name: Lint with prettier
        working-directory: ${{ inputs.working_directory }}
        run: |
          npx yarn lint
      - name: Run yarn test
        working-directory: ${{ inputs.working_directory }}
        run: |
          npx yarn test
