name: Frontend CI
on:
  workflow_call:
    inputs:
      working_directory:
        type: string
        required: false
        default: "."
      node_version:
        type: string
        required: true
    secrets:
      PACKAGE_GITHUB_TOKEN:
        required: true
      TECHONOMY_REPO_GITHUB_TOKEN:
        required: true

jobs:
  linting-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup node ${{ inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
      - name: Configure NPM package repository
        run: |
          npx yarn config set @techonomydev:registry https://npm.pkg.github.com/
          npm set https://npm.pkg.github.com/:_authToken ${{ secrets.PACKAGE_GITHUB_TOKEN }}
      - name: Configure git
        run: |
          git config --global url."https://${{ secrets.TECHNONOMY_REPO_GITHUB_TOKEN }}@github.com/".insteadOf "git@github.com:"
      - name: Install front-end dependencies
        run: |
          cd ${{ inputs.working_directory }} && npx yarn install
      - name: Lint with prettier
        run: |
          cd ${{ inputs.working_directory }} && npx yarn lint
      - name: Test with jest
        run: |
          cd ${{ inputs.working_directory }} && npx yarn test
