name: Frontend build
on:
  workflow_call:
    inputs:
      working_directory:
        type: string
        required: false
        default: "."
      artifact_name:
        type: string
        required: true
      artifact_path:
        type: string
        required: true
      node_version:
        type: string
        required: true
      env_file:
        type: string
        default: ''
        required: false
    secrets:
      PACKAGE_GITHUB_TOKEN:
        required: false
      TECHONOMY_REPOS_GITHUB_TOKEN:
        required: true

jobs:
  build:
    # Cancel any stale jobs
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TECHONOMY_REPOS_GITHUB_TOKEN }}
      - name: Setup node ${{ inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
      - name: Configure NPM package repository
        run: |
          npx yarn config set @techonomydev:registry https://npm.pkg.github.com/
          npm set https://npm.pkg.github.com/:_authToken ${{ secrets.TECHONOMY_REPOS_GITHUB_TOKEN }}
      - name: Configure git
        run: |
          git config --global url."https://${{ secrets.TECHONOMY_REPOS_GITHUB_TOKEN }}@github.com/".insteadOf git@github.com:
      - name: Configure environment file
        if: ${{ inputs.env_file != '' }}
        run: |
          cp ${{ inputs.env_file }} .env
          # Remove all potential other env files to avoid conflicts
          rm .env.*
      - name: Install frontend dependencies
        run: |
          npx yarn --cwd  ${{ inputs.working_directory }} install
      - name: Build frontend artifacts
        run: |
          npx yarn --cwd  ${{ inputs.working_directory }} build
        env:
          DISABLE_ESLINT_PLUGIN: true
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}
          retention-days: 1
