name: Publish Python package
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      python_version:
        type: string
        required: true
      pip_version:
        type: string
        required: false
        default: ">=23,<23.1"
      poetry_version:
        type: string
        required: false
        default: ">=1.4.0,<1.5"
      artifact_name:
        type: string
        required: false
      artifact_path:
        type: string
        required: false
    secrets:
      TECHONOMY_REPOS_GITHUB_TOKEN:
        required: true

jobs:
  publish-python-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.TECHONOMY_REPOS_GITHUB_TOKEN }}
      - name: Download static files
        if: "${{ inputs.artifact_name }}"
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: "${{ inputs.python_version }}"
      - name: Setup ssh:// to https:// mapping with a token
        run: |
          git config --global url."https://${{ secrets.TECHONOMY_REPOS_GITHUB_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
      - name: Install additional software
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libssl-dev libcurl4-openssl-dev ${{ inputs.apt_extra_packages }}
      - name: Install Python dependencies
        env:
          PYCURL_SSL_LIBRARY: openssl
        run: |
          pip3 install "pip${{ inputs.pip_version }}" "poetry${{ inputs.poetry_version }}"
          make install
      - name: Build Python package
        env:
          PYCURL_SSL_LIBRARY: openssl
        run: |
          source $(poetry env info --path)/bin/activate
          make dist
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.name }}
          path: dist
          retention-days: 7
